In [1]:
import numpy as np
np.random.seed(0)

In [2]:
from env.EV_Sce_Env import EV_Sce_Env

env = EV_Sce_Env('train_1', seed=0)
env.reset()

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\10199\\Study\\EV\\code\\code_mine\\MAPPO\\plan_2_test_on_mappo_mp\\env\\scenarios\\train_1.py'

In [ ]:
env.step([0, 0, 0, 0, 0])

([array([-0.14317115,  6.        ,  0.        ,  0.        ,  0.        ,
          0.        ]),
  array([-0.18382528,  6.        ,  0.        ,  0.        ,  0.        ,
          0.        ]),
  array([0.2725254, 8.       , 0.       , 0.       , 0.       , 1.       ]),
  array([0.43289467, 8.        , 0.        , 0.        , 0.        ,
         1.        ]),
  array([0.01918349, 8.        , 0.        , 0.        , 0.        ,
         1.        ])],
 array([-0.14317115,  6.        ,  0.        ,  0.        ,  0.        ,
        -0.18382528,  6.        ,  0.        ,  0.        ,  0.        ,
         0.2725254 ,  8.        ,  0.        ,  0.        ,  1.        ,
         0.43289467,  8.        ,  0.        ,  0.        ,  1.        ,
         0.01918349,  8.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ]),
 [array([-10]), array([-10]), array([-5]), array([-5]), array([-5])],
 [array([ True]),
  array([ True]),
  array([ True]),
  ar

In [ ]:
env.render()

Time: 3.1 h
O:None----CS_0:None----CS_1:None--------CS_2:[EV_0,EV_1]------D:[EV_2,EV_3,EV_4]
EV_0:
	 SOC:-0.14%   Pos:6   Reward:-10.00   Using time:0.00h   Charing times:0   Charing SOC:0.00%
	 Action_list:  [0, 0]
EV_1:
	 SOC:-0.18%   Pos:6   Reward:-10.00   Using time:0.00h   Charing times:0   Charing SOC:0.00%
	 Action_list:  [0, 0]
EV_2:
	 SOC:0.27%   Pos:8   Reward:-5.00   Using time:0.00h   Charing times:0   Charing SOC:0.00%
	 Action_list:  [0, 0, 0]
EV_3:
	 SOC:0.43%   Pos:8   Reward:-5.00   Using time:0.00h   Charing times:0   Charing SOC:0.00%
	 Action_list:  [0, 0, 0]
EV_4:
	 SOC:0.02%   Pos:8   Reward:-5.00   Using time:0.00h   Charing times:0   Charing SOC:0.00%
	 Action_list:  [0, 0, 0]
CS_0: 0.00	0.00	0.00	
CS_1: 0.00	0.00	0.00	
CS_2: 0.00	0.00	0.00	
Global_inf:  [0, 0, 0]


In [ ]:
env.agents[0].finish_trip

False