In [1]:
import numpy as np
np.random.seed(0)
from env.EV_Sce_Env import EV_Sce_Env

env = EV_Sce_Env('test_2', seed=0, ps=False)

In [2]:
env.reset()
agents_total_reward = np.array([0.0 for _ in range(env.agent_num)])
print(env.caction_list)

[1.5, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]


In [16]:
env.step(([10, 0], [4, 0]))

([array([0.5 , 0.5 , 5.25, 1.  , 3.45, 0.  , 0.  , 1.  , 0.  , 0.  , 0.  ]),
  array([0.2 , 0.5 , 1.2 , 0.  , 8.45, 0.  , 0.  , 0.  , 0.  , 1.  , 0.  ])],
 [array([[0.  , 0.  ],
         [3.45, 1.  ],
         [0.  , 0.  ],
         [8.45, 0.  ],
         [0.  , 0.  ]]),
  array([[0.  , 0.  ],
         [3.45, 0.  ],
         [0.  , 0.  ],
         [8.45, 1.  ],
         [0.  , 0.  ]])],
 [array([0, 0, 1, 0, 1]), array([0, 0, 0, 0, 1])],
 array([0.5 , 0.5 , 5.25, 1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.2 ,
        0.5 , 1.2 , 0.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 3.45,
        0.  , 8.45, 0.  ]),
 array([[0.  , 0.  , 0.  , 0.  ],
        [3.7 , 3.45, 1.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  ],
        [8.45, 8.45, 0.  , 1.  ],
        [0.  , 0.  , 0.  , 0.  ]]),
 [array([False]), array([False])],
 [array([-4.85]), array([0])],
 [array([-5.25]), array([-0.4])],
 [array([10]), array([0])],
 [array([1]), array([3])],
 [1],
 [True],
 [],
 [])

In [17]:
env.render()

Time: 1.55 h
EV_0:
	 SOC:0.500%   Pos:P1   Reward:-5.25000   Using time:5.250h   Charing times:1   Charing SOC:0.100%
	 Action_list:  [1, 10]
	 Action_type:  ['r', 'c']
	 Route:  ['0-1']
EV_1:
	 SOC:0.200%   Pos:2-3   Reward:-1.20000   Using time:1.200h   Charing times:0   Charing SOC:0.000%
	 Action_list:  [1, 0, 2, 0, 3]
	 Action_type:  ['r', 'c', 'r', 'c', 'r']
	 Route:  ['0-1', '1-2', '2-3']
CS_0: 0.000	0.000	
CS_1: 3.700	3.450	
CS_2: 0.000	0.000	
CS_3: 8.450	8.450	
CS_4: 0.000	0.000	
Global_inf:  [0, 3.4500000000000055, 0.0, 8.449999999999978, 0]
