In [93]:
import numpy as np
np.random.seed(0)
from env.EV_Sce_Env import EV_Sce_Env

env = EV_Sce_Env('test_2', seed=0, ps=False)

In [94]:
env.reset()
agents_total_reward = np.array([0.0 for _ in range(env.agent_num)])
print(env.caction_list)

[1.5, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]


In [98]:
obs_n, obs_feature_n, obs_mask_n, \
    share_obs, global_cs_feature, \
        done_n, creward_n, rreward_n, cact_n, ract_n, \
            activate_agent_ci, activate_to_cact, activate_agent_ri, activate_to_ract = env.step(([10], [4]))

for i, agent_i in enumerate(activate_agent_ci):
    pass
for i, agent_i in enumerate(activate_agent_ri):
    agents_total_reward[agent_i] += rreward_n[agent_i][0].copy()
                        
obs_n, obs_feature_n, obs_mask_n, \
    share_obs, global_cs_feature, \
        done_n, creward_n, rreward_n, cact_n, ract_n, \
            activate_agent_ci, activate_to_cact, activate_agent_ri, activate_to_ract, \
                agents_total_reward

([array([0.2 , 0.5 , 6.45, 1.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 1.  ])],
 [array([[0.  , 0.  ],
         [0.  , 0.  ],
         [0.  , 0.  ],
         [3.55, 0.  ],
         [0.  , 1.  ]])],
 [array([0, 0, 0, 0, 0])],
 array([0.2 , 0.5 , 6.45, 1.  , 1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  ,
        0.  , 0.  , 3.55, 0.  ]),
 array([[0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  ],
        [3.55, 3.55, 0.  ],
        [0.  , 0.  , 1.  ]]),
 [array([ True])],
 [array([-9.85])],
 [array([-6.2])],
 [array([10])],
 [array([4])],
 [0],
 [False],
 [0],
 [0],
 array([-11.45]))

In [96]:
env.render()

Time: 0.4 h
EV_0:
	 SOC:0.400%   Pos:0-1   Reward:-0.40000   Using time:0.400h   Charing times:0   Charing SOC:0.000%
	 Action_list:  [1]
	 Action_type:  ['r']
CS_0: 0.000	0.000	
CS_1: 4.600	4.600	
CS_2: 0.000	0.000	
CS_3: 9.600	9.600	
CS_4: 0.000	0.000	
Global_inf:  [0, 4.600000000000001, 0.0, 9.599999999999994, 0]
