In [1]:
import numpy as np
np.random.seed(0)
from env.EV_Sce_Env import EV_Sce_Env

env = EV_Sce_Env('test_2', seed=0, ps=False)

In [2]:
env.reset()
agents_total_reward = np.array([0.0 for _ in range(env.agent_num)])
print(env.caction_list)

[1.5, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]


In [14]:
env.step(([0, 0], [4, 4]))

([array([0.5  , 0.5  , 2.275, 1.   , 0.   , 1.   , 0.   , 0.   , 0.   ,
         0.   , 1.   ]),
  array([0.5  , 0.5  , 2.275, 1.   , 0.   , 1.   , 0.   , 0.   , 0.   ,
         0.   , 1.   ])],
 [array([[0.  , 0.  ],
         [2.33, 0.  ],
         [0.  , 0.  ],
         [7.33, 0.  ],
         [0.  , 1.  ]]),
  array([[0.  , 0.  ],
         [2.33, 0.  ],
         [0.  , 0.  ],
         [7.33, 0.  ],
         [0.  , 1.  ]])],
 [array([0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0])],
 array([0.5  , 0.5  , 2.275, 1.   , 1.   , 0.   , 0.   , 0.   , 0.   ,
        1.   , 0.5  , 0.5  , 2.275, 1.   , 1.   , 0.   , 0.   , 0.   ,
        0.   , 1.   , 0.   , 2.33 , 0.   , 7.33 , 0.   ]),
 array([[0.  , 0.  , 0.  , 0.  ],
        [2.33, 2.33, 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  ],
        [7.33, 7.33, 0.  , 0.  ],
        [0.  , 0.  , 1.  , 1.  ]]),
 [array([ True]), array([ True])],
 [array([-0.875]), array([-0.875])],
 [array([-0.6]), array([-0.6])],
 [array([13]), array([13])],
 [array([4])

In [15]:
env.render()

Time: 2.67 h
EV_0:
	 SOC:0.500%   Pos:2-4   Reward:-2.27500   Using time:2.275h   Charing times:1   Charing SOC:0.350%
	 Action_list:  [1, 0, 2, 13, 4]
	 Action_type:  ['r', 'c', 'r', 'c', 'r']
	 Route:  ['0-1', '1-2', '2-4']
EV_1:
	 SOC:0.500%   Pos:2-4   Reward:-2.27500   Using time:2.275h   Charing times:1   Charing SOC:0.350%
	 Action_list:  [1, 0, 2, 13, 4]
	 Action_type:  ['r', 'c', 'r', 'c', 'r']
	 Route:  ['0-1', '1-2', '2-4']
CS_0: 0.000	0.000	
CS_1: 2.330	2.330	
CS_2: 0.000	0.000	
CS_3: 7.330	7.330	
CS_4: 0.000	0.000	
Global_inf:  [0, 2.330000000000057, 0, 7.330000000000057, 0]
